CREATE TABLE `입찰목록` (
    `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 식별자',
    `번호` VARCHAR(20) COMMENT '프로젝트 식별 번호',
    `단계` VARCHAR(50) COMMENT '프로젝트 진행 단계',
    `용역구분` VARCHAR(100) COMMENT '용역 종류',
    `접수방법` VARCHAR(50) COMMENT '입찰 접수 방법 (이메일, 방문접수, 우편 등)',
    `업체` VARCHAR(100) COMMENT '입찰 업체명',
    `지역` VARCHAR(100) COMMENT '사업 수행 지역',
    `공고번호` VARCHAR(100) COMMENT '입찰 공고 번호',
    `용역명` VARCHAR(255) COMMENT '프로젝트/용역 명칭',
    `개시일` DATE COMMENT '입찰 시작일',
    `마감일` DATE COMMENT '입찰 마감일',
    `제출일` DATE COMMENT '서류 제출일',
    `개찰일` DATE COMMENT '개찰일',
    `기초금액` DECIMAL(15, 2) COMMENT '사업 기초 금액 (예산)',
    `낙찰하한율` DECIMAL(5, 2) COMMENT '낙찰 가능 최저 비율 (%)',
    `예가_하한` DECIMAL(5, 2) COMMENT '예정가격 하한 범위 (%)',
    `예가_상한` DECIMAL(5, 2) COMMENT '예정가격 상한 범위 (%)',
    `투찰금액` DECIMAL(15, 2) COMMENT '실제 투찰 금액',
    `투찰율` DECIMAL(10, 4) COMMENT '투찰금액 대비 기초금액 비율',
    `낙찰금액` DECIMAL(15, 2) COMMENT '최종 낙찰 금액',
    `낙찰율` DECIMAL(10, 4) COMMENT '낙찰금액 대비 기초금액 비율',
    `낙찰사` VARCHAR(100) COMMENT '낙찰 업체명',
    `낙찰사정율` DECIMAL(10, 4) COMMENT '낙찰 적정성 비율',
    `추천요율` DECIMAL(10, 4) COMMENT '추천 적정 비율',
    `일맥투찰율` DECIMAL(10, 4) COMMENT '일맥 업체 투찰율',
    `사업수행_취득점수` DECIMAL(10, 2) COMMENT '사업 수행 평가 점수',
    `사업수행_총점` DECIMAL(10, 2) COMMENT '사업 수행 평가 총점',
    `등수` INT COMMENT '입찰 결과 순위',
    `입찰전체수` INT COMMENT '전체 입찰 참여 업체 수',
    `평균가` DECIMAL(15, 2) COMMENT '전체 입찰의 평균 금액',
    `차이` DECIMAL(15, 2) COMMENT '투찰액과 평균가의 차이',
    `특이사항` VARCHAR(255) COMMENT '추첨제, 투찰포기, 취소 등 특이사항',
    `비고` TEXT COMMENT '추가 정보',
    `등록일시` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '데이터 등록 일시',
    `수정일시` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '데이터 수정 일시',
    INDEX `idx_공고번호` (`공고번호`),
    INDEX `idx_업체` (`업체`),
    INDEX `idx_용역명` (`용역명`),
    INDEX `idx_개시일` (`개시일`),
    INDEX `idx_마감일` (`마감일`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='입찰 정보 목록 데이터';
