CREATE TABLE `notices_g2b` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '자동증가 기본키',
  `bid_ntce_no` varchar(40) NOT NULL COMMENT '입찰공고번호 - 조달청나라장터 공고건 관리번호',
  `bid_ntce_ord` varchar(3) DEFAULT NULL COMMENT '입찰공고차수 - 재공고/재입찰 시 증가',
  `re_ntce_yn` char(1) DEFAULT NULL COMMENT '재공고여부 (Y/N)',
  `rgst_ty_nm` varchar(100) DEFAULT NULL COMMENT '등록유형명 - 조달청 또는 나라장터 자체 공고건',
  `ntce_kind_nm` varchar(100) DEFAULT NULL COMMENT '공고종류명 - 일반/변경/취소/재입찰/연기/긴급 등',
  `intrbid_yn` char(1) DEFAULT NULL COMMENT '국제입찰여부 (Y/N)',
  `bid_ntce_dt` datetime DEFAULT NULL COMMENT '입찰공고일시 - 공고서를 공고한 일시',
  `ref_no` varchar(105) DEFAULT NULL COMMENT '참조번호 - 자체 전자조달시스템 관리번호',
  `bid_ntce_nm` varchar(500) NOT NULL COMMENT '입찰공고명 - 공사명/사업명',
  `ntce_instt_cd` varchar(7) DEFAULT NULL COMMENT '공고기관코드 - 행자부코드 또는 조달청 부여코드',
  `ntce_instt_nm` varchar(200) DEFAULT NULL COMMENT '공고기관명 - 공고하는 기관명',
  `dminstt_cd` varchar(7) DEFAULT NULL COMMENT '수요기관코드 - 행자부코드 또는 조달청 부여코드',
  `dminstt_nm` varchar(200) DEFAULT NULL COMMENT '수요기관명 - 실제 계약을 의뢰한 기관명',
  `bid_methd_nm` varchar(200) DEFAULT NULL COMMENT '입찰방식명 - 전자입찰/직찰/우편 등',
  `cntrct_cncls_mthd_nm` varchar(200) DEFAULT NULL COMMENT '계약체결방법명 - 일반경쟁/제한경쟁/지명경쟁/수의계약',
  `ntce_instt_ofcl_nm` varchar(35) DEFAULT NULL COMMENT '공고기관담당자명',
  `ntce_instt_ofcl_tel_no` varchar(25) DEFAULT NULL COMMENT '공고기관담당자전화번호',
  `ntce_instt_ofcl_email_adrs` varchar(100) DEFAULT NULL COMMENT '공고기관담당자이메일주소',
  `exctv_nm` varchar(35) DEFAULT NULL COMMENT '집행관명',
  `bid_qlfct_rgst_dt` datetime DEFAULT NULL COMMENT '입찰참가자격등록마감일시',
  `cmmn_spldmd_agrmnt_rcptdoc_methd` varchar(30) DEFAULT NULL COMMENT '공동수급협정서접수방식 - 없음/전자문서/수기',
  `cmmn_spldmd_agrmnt_clse_dt` datetime DEFAULT NULL COMMENT '공동수급협정마감일시',
  `cmmn_spldmd_corp_rgn_lmt_yn` char(1) DEFAULT NULL COMMENT '공동수급업체지역제한여부 (Y/N)',
  `bid_begin_dt` datetime DEFAULT NULL COMMENT '입찰개시일시 - 입찰서 제출 시작시간',
  `bid_clse_dt` datetime DEFAULT NULL COMMENT '입찰마감일시 - 입찰서 제출 마감시간',
  `openg_dt` datetime DEFAULT NULL COMMENT '개찰일시 - 개찰 수행 가능 시작일시',
  `ntce_spec_doc_url1` text DEFAULT NULL COMMENT '공고규격서URL1',
  `ntce_spec_doc_url2` text DEFAULT NULL COMMENT '공고규격서URL2',
  `ntce_spec_doc_url3` text DEFAULT NULL COMMENT '공고규격서URL3',
  `ntce_spec_doc_url4` text DEFAULT NULL COMMENT '공고규격서URL4',
  `ntce_spec_doc_url5` text DEFAULT NULL COMMENT '공고규격서URL5',
  `ntce_spec_doc_url6` text DEFAULT NULL COMMENT '공고규격서URL6',
  `ntce_spec_doc_url7` text DEFAULT NULL COMMENT '공고규격서URL7',
  `ntce_spec_doc_url8` text DEFAULT NULL COMMENT '공고규격서URL8',
  `ntce_spec_doc_url9` text DEFAULT NULL COMMENT '공고규격서URL9',
  `ntce_spec_doc_url10` text DEFAULT NULL COMMENT '공고규격서URL10',
  `ntce_spec_file_nm1` varchar(256) DEFAULT NULL COMMENT '공고규격파일명1',
  `ntce_spec_file_nm2` varchar(256) DEFAULT NULL COMMENT '공고규격파일명2',
  `ntce_spec_file_nm3` varchar(256) DEFAULT NULL COMMENT '공고규격파일명3',
  `ntce_spec_file_nm4` varchar(256) DEFAULT NULL COMMENT '공고규격파일명4',
  `ntce_spec_file_nm5` varchar(256) DEFAULT NULL COMMENT '공고규격파일명5',
  `ntce_spec_file_nm6` varchar(256) DEFAULT NULL COMMENT '공고규격파일명6',
  `ntce_spec_file_nm7` varchar(256) DEFAULT NULL COMMENT '공고규격파일명7',
  `ntce_spec_file_nm8` varchar(256) DEFAULT NULL COMMENT '공고규격파일명8',
  `ntce_spec_file_nm9` varchar(256) DEFAULT NULL COMMENT '공고규격파일명9',
  `ntce_spec_file_nm10` varchar(256) DEFAULT NULL COMMENT '공고규격파일명10',
  `rbid_permsn_yn` char(1) DEFAULT NULL COMMENT '재입찰허용여부 (Y/N)',
  `pq_appl_doc_rcpt_mthd_nm` varchar(30) DEFAULT NULL COMMENT 'PQ신청서접수방법명',
  `pq_appl_doc_rcpt_dt` datetime DEFAULT NULL COMMENT 'PQ신청서접수일시',
  `tp_eval_appl_mthd_nm` varchar(30) DEFAULT NULL COMMENT 'TP심사신청방법명',
  `tp_eval_appl_clse_dt` datetime DEFAULT NULL COMMENT 'TP심사신청마감일시',
  `jntcontrct_duty_rgn_nm1` varchar(200) DEFAULT NULL COMMENT '공동도급의무지역명1',
  `jntcontrct_duty_rgn_nm2` varchar(200) DEFAULT NULL COMMENT '공동도급의무지역명2',
  `jntcontrct_duty_rgn_nm3` varchar(200) DEFAULT NULL COMMENT '공동도급의무지역명3',
  `rgn_duty_jntcontrct_rt` varchar(20) DEFAULT NULL COMMENT '지역의무공동도급비율 (%)',
  `dtls_bid_yn` char(1) DEFAULT NULL COMMENT '내역입찰여부 (Y/N)',
  `bid_prtcpt_lmt_yn` char(1) DEFAULT NULL COMMENT '입찰참가제한여부 (Y/N)',
  `prearng_prce_dcsn_mthd_nm` varchar(20) DEFAULT NULL COMMENT '예정가격결정방법명 - 복수예가/단일예가',
  `tot_prdprc_num` varchar(20) DEFAULT NULL COMMENT '총예가건수',
  `drwt_prdprc_num` varchar(20) DEFAULT NULL COMMENT '추첨예가건수',
  `asign_bdgt_amt` decimal(20,0) DEFAULT NULL COMMENT '배정예산금액 (원) - 배정된 예산액',
  `presmpt_prce` decimal(20,0) DEFAULT NULL COMMENT '추정가격 (원) - 부가세/수수료 제외 금액',
  `openg_plce` varchar(100) DEFAULT NULL COMMENT '개찰장소',
  `dcmtg_oprtn_dt` datetime DEFAULT NULL COMMENT '설명회실시일시',
  `dcmtg_oprtn_plce` varchar(100) DEFAULT NULL COMMENT '설명회실시장소',
  `bid_ntce_dtl_url` text DEFAULT NULL COMMENT '입찰공고상세URL - 나라장터 상세화면 링크',
  `bid_ntce_url` varchar(500) DEFAULT NULL COMMENT '입찰공고URL',
  `bid_prtcpt_fee_paymnt_yn` varchar(30) DEFAULT NULL COMMENT '입찰참가수수료납부여부',
  `bid_prtcpt_fee` decimal(15,0) DEFAULT NULL COMMENT '입찰참가수수료 (원)',
  `bid_grntymny_paymnt_yn` varchar(30) DEFAULT NULL COMMENT '입찰보증금납부여부',
  `crdtr_nm` varchar(200) DEFAULT NULL COMMENT '채권자명 - 입찰보증금 보증채권자명',
  `ppsw_gnrl_srvce_yn` char(1) DEFAULT NULL COMMENT '조달청일반용역여부 (Y/N)',
  `srvce_div_nm` varchar(30) DEFAULT NULL COMMENT '용역구분명 - 일반용역/기술용역',
  `prdct_clsfc_lmt_yn` char(1) DEFAULT NULL COMMENT '물품분류제한여부 (Y/N)',
  `mnfct_yn` char(1) DEFAULT NULL COMMENT '제조여부 (Y/N)',
  `purchs_obj_prdct_list` text DEFAULT NULL COMMENT '구매대상물품목록',
  `unty_ntce_no` varchar(11) DEFAULT NULL COMMENT '통합공고번호',
  `cmmn_spldmd_methd_cd` varchar(15) DEFAULT NULL COMMENT '공동수급방식코드',
  `cmmn_spldmd_methd_nm` varchar(100) DEFAULT NULL COMMENT '공동수급방식명',
  `std_ntce_doc_url` varchar(256) DEFAULT NULL COMMENT '표준공고서URL',
  `brffc_bidprc_permsn_yn` char(1) DEFAULT NULL COMMENT '지사투찰허용여부 (Y/N)',
  `dsgnt_cmpt_yn` char(1) DEFAULT NULL COMMENT '지명경쟁여부 (Y/N)',
  `arslt_cmpt_yn` char(1) DEFAULT NULL COMMENT '실적경쟁여부 (Y/N)',
  `pq_eval_yn` char(1) DEFAULT NULL COMMENT 'PQ심사여부 (Y/N)',
  `tp_eval_yn` char(1) DEFAULT NULL COMMENT 'TP심사여부 (Y/N)',
  `ntce_dscrpt_yn` char(1) DEFAULT NULL COMMENT '공고설명여부 (Y/N)',
  `rsrvtn_prce_re_mkng_mthd_nm` varchar(50) DEFAULT NULL COMMENT '예비가격재작성방법명',
  `arslt_appl_doc_rcpt_mthd_nm` varchar(50) DEFAULT NULL COMMENT '실적신청서접수방법명',
  `arslt_reqstdoc_rcpt_dt` datetime DEFAULT NULL COMMENT '실적신청서접수일시',
  `order_plan_unty_no` varchar(35) DEFAULT NULL COMMENT '발주계획통합번호',
  `sucsfbid_lwlt_rate` decimal(8,3) DEFAULT NULL COMMENT '낙찰하한율 (%)',
  `rgst_dt` datetime DEFAULT NULL COMMENT '등록일시 - 공고 등록일시',
  `bf_spec_rgst_no` varchar(10) DEFAULT NULL COMMENT '사전규격등록번호',
  `info_biz_yn` char(1) DEFAULT NULL COMMENT '정보화사업여부 (Y/N)',
  `sucsfbid_mthd_cd` varchar(9) DEFAULT NULL COMMENT '낙찰방법코드',
  `sucsfbid_mthd_nm` varchar(200) DEFAULT NULL COMMENT '낙찰방법명 - 낙찰자 결정방법',
  `chg_dt` datetime DEFAULT NULL COMMENT '변경일시',
  `dminstt_ofcl_email_adrs` varchar(100) DEFAULT NULL COMMENT '수요기관담당자이메일주소',
  `indstryty_lmt_yn` char(1) DEFAULT NULL COMMENT '업종제한여부 (Y/N)',
  `chg_ntce_rsn` text DEFAULT NULL COMMENT '변경공고사유',
  `rbid_openg_dt` datetime DEFAULT NULL COMMENT '재입찰개찰일시',
  `vat` decimal(20,0) DEFAULT NULL COMMENT '부가가치세 (원)',
  `induty_vat` decimal(20,0) DEFAULT NULL COMMENT '주공종부가가치세 (원)',
  `rgn_lmt_bid_locplc_jdgm_bss_cd` varchar(10) DEFAULT NULL COMMENT '지역제한입찰지역판단기준코드',
  `rgn_lmt_bid_locplc_jdgm_bss_nm` varchar(50) DEFAULT NULL COMMENT '지역제한입찰지역판단기준명',
  `pub_prcrmnt_lrg_clsfc_nm` varchar(100) DEFAULT NULL COMMENT '공공조달대분류명',
  `pub_prcrmnt_mid_clsfc_nm` varchar(100) DEFAULT NULL COMMENT '공공조달중분류명',
  `pub_prcrmnt_clsfc_no` varchar(10) DEFAULT NULL COMMENT '공공조달분류번호',
  `pub_prcrmnt_clsfc_nm` varchar(100) DEFAULT NULL COMMENT '공공조달분류명',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '레코드 생성일시',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '레코드 수정일시',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bid_ntce_no_ord` (`bid_ntce_no`, `bid_ntce_ord`),
  KEY `idx_bid_ntce_dt` (`bid_ntce_dt`),
  KEY `idx_bid_clse_dt` (`bid_clse_dt`),
  KEY `idx_openg_dt` (`openg_dt`),
  KEY `idx_ntce_instt_cd` (`ntce_instt_cd`),
  KEY `idx_dminstt_cd` (`dminstt_cd`),
  KEY `idx_rgst_dt` (`rgst_dt`),
  KEY `idx_pub_prcrmnt_clsfc_no` (`pub_prcrmnt_clsfc_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='입찰공고 정보 - 공공데이터포털 입찰공고 API 데이터';